# Generated by Django 4.0.4 on 2023-10-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfoPreprocessed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.TextField(blank=True, null=True)),
                ('center_code', models.IntegerField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfoRaw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.TextField(blank=True, null=True)),
                ('course_code', models.TextField(blank=True, null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_cover_file', models.TextField(blank=True, null=True)),
                ('course_level', models.IntegerField(blank=True, null=True)),
                ('course_info', models.TextField(blank=True, null=True)),
                ('use_flag', models.TextField(blank=True, null=True)),
                ('register_datetime', models.TextField(blank=True, null=True)),
                ('updated_datetime', models.TextField(blank=True, null=True)),
                ('register_agent', models.TextField(blank=True, null=True)),
                ('course_provider', models.TextField(blank=True, null=True)),
                ('syllabus', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('center_code', models.IntegerField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRatingPreprocessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.TextField(blank=True, null=True)),
                ('course_code', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRatingRaw',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.TextField(blank=True, null=True)),
                ('chapter_code', models.TextField(blank=True, null=True)),
                ('student', models.TextField(blank=True, null=True)),
                ('course_code', models.TextField(blank=True, null=True)),
                ('center_code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawTablesInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tableName', models.TextField()),
                ('numData', models.IntegerField()),
                ('lastPage', models.IntegerField()),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagsPreprocessed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagsRaw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserListPreprocessed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('is_active', models.TextField(blank=True, null=True)),
                ('member_id', models.TextField(blank=True, null=True)),
                ('member_permanent_address', models.TextField(blank=True, null=True)),
                ('member_temporary_address', models.TextField(blank=True, null=True)),
                ('member_birthdate', models.TextField(blank=True, null=True)),
                ('member_phone', models.TextField(blank=True, null=True)),
                ('use_flag', models.IntegerField(blank=True, null=True)),
                ('register_datetime', models.TextField(blank=True, null=True)),
                ('register_agent', models.TextField(blank=True, null=True)),
                ('updated_datetime', models.TextField(blank=True, null=True)),
                ('is_teacher', models.IntegerField(blank=True, null=True)),
                ('is_student', models.IntegerField(blank=True, null=True)),
                ('is_center_admin', models.IntegerField(blank=True, null=True)),
                ('member_memo', models.TextField(blank=True, null=True)),
                ('member_avatar', models.TextField(blank=True, null=True)),
                ('member_department', models.TextField(blank=True, null=True)),
                ('member_position', models.TextField(blank=True, null=True)),
                ('center_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserListRaw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('is_active', models.TextField(blank=True, null=True)),
                ('member_id', models.TextField(blank=True, null=True)),
                ('member_permanent_address', models.TextField(blank=True, null=True)),
                ('member_temporary_address', models.TextField(blank=True, null=True)),
                ('member_birthdate', models.TextField(blank=True, null=True)),
                ('member_phone', models.TextField(blank=True, null=True)),
                ('use_flag', models.IntegerField(blank=True, null=True)),
                ('register_datetime', models.TextField(blank=True, null=True)),
                ('register_agent', models.TextField(blank=True, null=True)),
                ('updated_datetime', models.TextField(blank=True, null=True)),
                ('is_teacher', models.IntegerField(blank=True, null=True)),
                ('is_student', models.IntegerField(blank=True, null=True)),
                ('is_center_admin', models.IntegerField(blank=True, null=True)),
                ('member_memo', models.TextField(blank=True, null=True)),
                ('member_avatar', models.TextField(blank=True, null=True)),
                ('member_department', models.TextField(blank=True, null=True)),
                ('member_position', models.TextField(blank=True, null=True)),
                ('center_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
