# Generated by Django 4.0.4 on 2023-10-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessingComponent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseratingpreprocessed',
            name='course_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingpreprocessed',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingpreprocessed',
            name='student',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingraw',
            name='center_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingraw',
            name='chapter_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingraw',
            name='course_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingraw',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingraw',
            name='student',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
