# Generated by Django 4.0.4 on 2023-10-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessingComponent', '0004_alter_userlistpreprocessed_register_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistpreprocessed',
            name='member_birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
