# Generated by Django 4.2.6 on 2023-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessingComponent', '0005_alter_userlistpreprocessed_member_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfopreprocessed',
            name='course_name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
